<?php

define("ORDER_NOT_APPROVED", "10000");
define("ORDER_REJECTED", "10001");
define("ORDER_REJECTED_ADMIN", "10002");
define("ORDER_NUMBER_NOT_FOUND", "10002");
define("UNAUTHORISED", "401");
define("SUCCESS", "0");
define("INFORMATION_NOT_FOUND", "404");
define("ORDER_CLEARED", 3001);
define("BAD_REQUEST", "501");
define("DATABASE_ERROR", "501");
define("DUPLICATE_TRANSACTION", "10003");
define("NOT_ALLOWED_METHOD", "100004");
define("INTERNAL_SERVER_ERROR", "500");

//global user action constants
define("CLIENT_REJECT_OPERATION", 1003);
define("CLIENT_CANCEL_OPERATION", 1002);
define("CLIENT_ACCEPT_OPERATION", 1001);
define("CLIENT_PENDING_OPERATION", 1000);
define("GENERAL_PENDING", 0000);

define("SYS_REJECT_OPERATION", 2002);
define("SYS_CANCEL_OPERATION", 2002);
define("SYS_ACCEPT_OPERATION", 2001);
define("SYS_PENDING_OPERATION", 2000);

define("VENDOR_REJECT_OPERATION", 2002);
define("VENDOR_CANCEL_OPERATION", 2002);
define("VENDOR_ACCEPT_OPERATION", 2001);
define("VENDOR_PENDING_OPERATION", 2000);

define("ORDER_MARKUP", "ORDER_MARKUP");
define("PROMOTE_ITEM", "PROMOTE_ITEM");
define("FINE", "FINE");
